//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;   

    public partial class ResortsNotReserved
    {
        [Key, Column(Order = 0)]       
        public short F_HCODE { get; set; }
        [Key, Column(Order = 1)]
        public short F_WEEK { get; set; }
        [Key, Column(Order = 2)]
        public short F_FCODE { get; set; }
        [Display(Name = "اسم المصيف")]
        public string HOLDAY_NAME { get; set; }
        [Display(Name = " وصف الوحده")]
        public string F_FLAT_DESC { get; set; }
        [Display(Name = "  تكلفة الاسبوع")]
        public decimal F_WEEKCOST { get; set; }
        [Display(Name = "   مبلغ التأمين")]
        public Nullable<decimal> F_INSURCOST { get; set; }
        [Display(Name = "الفترة من")]
        public string F_FROM { get; set; }
        [Display(Name = "الى")]
        public string F_TO { get; set; }

        [NotMapped]
        public List<V_FLAT_PIC> FlatPics { get; set; }

        [NotMapped]
        public List<V_FLAT_PIC> FlatVideos { get; set; }

    }
}
