//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class V_DET_ACTIV
    {
        public decimal ID { get; set; }
        [Display(Name = "الكود")]
        public decimal F_CODE { get; set; }
        [Display(Name = "الاسم")]
        public string F_NAME { get; set; }
        [Display(Name = " تاريخ بداية الرحلة ")]
        [DisplayFormat(DataFormatString = "{0:dd MM yyyy}")]
        public Nullable<System.DateTime> TRIP_FROM { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MM yyyy}")]
        public Nullable<System.DateTime> TRIP_TO { get; set; }
        [Display(Name = "تكلفة المرافق")]
        public Nullable<decimal> M_COST { get; set; }
        [Display(Name = "تكلفة العضو")]
        public Nullable<decimal> F_COST { get; set; }
        [Display(Name = "تكلفة الطفل")]
        public Nullable<decimal> K_COST { get; set; }
        [Display(Name = "تكلفة غير العضو")]
        public Nullable<decimal> NO_PERSON { get; set; }
        [Display(Name = " تاريخ بداية الحجز ")]
        [DisplayFormat(DataFormatString = "{0:dd MM yyyy}")]
        public Nullable<System.DateTime> START_DATE { get; set; }
        [Display(Name = " تاريخ نهاية الحجز ")]
        [DisplayFormat(DataFormatString = "{0:dd MM yyyy}")]
        public Nullable<System.DateTime> END_DATE { get; set; }
        [Display(Name = "الدمغة")]
        public Nullable<decimal> F_STAMP { get; set; }
        [Display(Name = "مصاريف ادارية")]
        public Nullable<decimal> F_EDARYA { get; set; }
        [Display(Name = "الفرع")]
        public Nullable<byte> BRANCH_ACTIV { get; set; }
        [Display(Name = "السنة")]
        public Nullable<short> F_YEAR { get; set; }
    }
}
