//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class V_T_DIFFMEMBER
    {
       // [Key]
        public int F_CODE { get; set; }
        [Display(Name = "السنة")]
        public short F_YEAR { get; set; }
        [Display(Name = "التاريخ")]
        [DisplayFormat(DataFormatString = "{0:dd MM yyyy}")]
        public Nullable<System.DateTime> DATE_DIFF { get; set; }
        [Display(Name = "المبلغ")]
        public Nullable<decimal> VALUE { get; set; }
        [Display(Name = "ملاحظات")]
        public string NOTES { get; set; }
        [Display(Name = "تقسيط")]
        public Nullable<decimal> F_ISPAY_PRCENT { get; set; }
    }
}
