//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GUIDE_MAIN
    {
        public decimal F_CODE { get; set; }
        public string F_INSTITUTION_NAME { get; set; }
        public Nullable<decimal> F_GUIDE_ID { get; set; }
        public short F_YEAR { get; set; }
    }
}
