//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_KHAZNA_ACTIVITY
    {
        public Nullable<decimal> RECIPT_NO { get; set; }
        public Nullable<decimal> F_USER { get; set; }
        public Nullable<decimal> F_BRANCH { get; set; }
        public Nullable<decimal> F_MEM { get; set; }
        public Nullable<decimal> F_ID { get; set; }
        public Nullable<System.DateTime> TRIP_FROM { get; set; }
        public Nullable<System.DateTime> TRIP_TO { get; set; }
        public Nullable<decimal> M_COST { get; set; }
        public Nullable<decimal> F_COST { get; set; }
        public Nullable<decimal> NO_F { get; set; }
        public Nullable<decimal> K_COST { get; set; }
        public Nullable<decimal> NO_K { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<short> RECIEPT_YEAR { get; set; }
        public Nullable<System.DateTime> RECIEPT_DATE { get; set; }
        public Nullable<decimal> F_STAMP { get; set; }
        public Nullable<decimal> F_EDARYA { get; set; }
        public Nullable<decimal> COL_FK { get; set; }
        public decimal ACTIV_PK { get; set; }
        public Nullable<short> F_YEAR { get; set; }
        public Nullable<decimal> F_CODE { get; set; }
    }
}
