//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MAS_ACTIV
    {
        public decimal CODE { get; set; }
        public string F_NAME { get; set; }
        public short F_YEAR { get; set; }
        public string URL_TRIP_PIC { get; set; }
    }
}
