//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class V_MEDICAL_GUIDES
    {
        public decimal F_CODE { get; set; }
        [Display(Name = "السنه")]
        public short F_YEAR { get; set; }
        [Display(Name = "العنوان")]
        public string F_ADDREE { get; set; }
        [Display(Name = "نسبه الخصم")]
        public Nullable<decimal> F_RATIO { get; set; }
        public Nullable<decimal> F_GAV { get; set; }
        public Nullable<decimal> F_CENTER { get; set; }
        [Display(Name = "الموبيل ")]
        public string MOBILS { get; set; }
        [Display(Name = "التليفون ")]
        public string PHONES { get; set; }
        [Display(Name = "الفاكس")]
        public Nullable<decimal> F_FAX { get; set; }
        [Display(Name = "اسم المحافظه")]
        public string GOV_NAME { get; set; }
        [Display(Name = "اسم المركز")]
        public string CENTER_NAME { get; set; }
        public decimal F_CODE_MAIN { get; set; }
        [Display(Name = "اسم الدليل")]
        public string F_INSTITUTION_NAME { get; set; }
        public Nullable<decimal> F_GUIDE_ID { get; set; }
    }
}
