//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class V_MEMBER_INFO
    {
        [Key]
        public decimal F_CODE { get; set; }
        public string F_NAME { get; set; }
        [Display(Name = "رقم الشعبة")]
        public decimal F_BRANCHNO { get; set; }
        [Display(Name = "الشعبة")]
        public string BRANCH { get; set; }
        [Display(Name = "فرع العضو ")]
        public string BRANCHGOV { get; set; }
        public Nullable<decimal> F_LATEPAY { get; set; }
        public Nullable<decimal> F_PAYEAR { get; set; }
        public Nullable<decimal> F_MAINWRKSIDE { get; set; }

    }
}
