//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MEDICAL_GUIDE
    {
        public byte GUIDE_CODE { get; set; }
        public string CODENAME { get; set; }
        public decimal MAIN_CODE { get; set; }
        public string F_INSTITUTION_NAME { get; set; }
        public decimal DTL_CODE { get; set; }
        public string NAMEDTL { get; set; }
        public short F_YEAR { get; set; }
        public string F_ADDREE { get; set; }
        public string F_RATIO { get; set; }
        public string F_GAV { get; set; }
        public string F_CENTER { get; set; }
        public Nullable<long> F_MOBIL1 { get; set; }
        public Nullable<long> F_MOBIL2 { get; set; }
        public string F_MOBIL3 { get; set; }
        public string F_PHONE1 { get; set; }
        public Nullable<long> F_PHONE2 { get; set; }
        public string F_PHONE3 { get; set; }
        public string F_FAX { get; set; }
        public string GOV_NAME { get; set; }
        public string CENTER_NAME { get; set; }
    }
}
