//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PARTICIPATION_NEW_CATEGORY_2
    {
        public Nullable<decimal> F_MIN { get; set; }
        public Nullable<decimal> F_MAX { get; set; }
        public decimal F_VALUE { get; set; }
        public Nullable<decimal> F_SERVICE_BOX { get; set; }
        public Nullable<decimal> F_STAMP { get; set; }
        public Nullable<decimal> F_JOIN_MONEY { get; set; }
        public Nullable<decimal> F_ADMINI_MONEY { get; set; }
        public Nullable<decimal> NAWIA { get; set; }
        public Nullable<decimal> F_CD { get; set; }
        public Nullable<decimal> F_ESSP_CARD { get; set; }
        public string F_CLASS { get; set; }
    }
}
