//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class V_RESERVATION_RESORT
    {
      //  [Key, Column(Order = 0)]       
        public decimal RECIEPT_NO { get; set; }
       // [Key, Column(Order = 1)]
        public short RECIEPT_YEAR { get; set; }
        public System.DateTime RECIEPT_DATE { get; set; }
        public decimal BRANCH_NO { get; set; }
        public decimal USER_CODE { get; set; }
        public decimal F_MEM { get; set; }
        public short HOLIDAY_CODE { get; set; }
        public short HOLIDAY_YEAR { get; set; }
        public short FLAT_CODE { get; set; }
        public byte WEEK_NO { get; set; }
        public decimal FLAT_VALUE { get; set; }
        public Nullable<decimal> INSURE_VALUE { get; set; }
        public decimal RECIEPT_VALUE { get; set; }
        public Nullable<bool> CANCEL { get; set; }
        public Nullable<byte> DISCOUNT { get; set; }
        public Nullable<decimal> F_STAMP { get; set; }
        public decimal RES_PK { get; set; }
    }
}
