//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class T_REQUESTS
    {
        [Key]
        public int F_ID { get; set; }
        [Display(Name = "رقم القيد")]
        public long F_MEM_ID { get; set; }

        //[Required(ErrorMessage = "الاسم مطلوب")]
        [Display(Name = "اسم العضو")]
        public string F_MEM_NAME { get; set; }
        [Display(Name = "رقم الطلب")]
        public int F_REQUEST_ID { get; set; }
        [Display(Name = "تاريخ الطلب")]
        public DateTime F_REQUEST_DATE { get; set; }

        [Display(Name = "تاريخ الطباعة")]
        public DateTime? F_PRINT_DATE { get; set; }
        [Required]
        [Display(Name = "رقم الموبيل")]       
        public string F_MOBILE_NO { get; set; }
        [Required]
        [Display(Name = "الرقم القومى ")]
        public string F_NATIONAL_ID { get; set; }
        [Display(Name = "عنوان الطلب او الشكوى")]
        public string F_TITTLE { get; set; }
        [Required]
        [Display(Name = "نص الطلب")]
        public string F_NOTES { get; set; }
        public short F_STATUS { get; set; }
        public int F_USER_ID { get; set; }
    }

    public partial class V_REQUESTS
    {
        [Key]
        public int F_ID { get; set; }
        [Display(Name = "رقم القيد")]
        public long F_MEM_ID { get; set; }
        [Display(Name = "اسم العضو")]
        public string F_MEM_NAME { get; set; }
        [Display(Name = "رقم الطلب")]
        public int F_REQUEST_ID { get; set; }
        [Display(Name = "تاريخ الطلب")]
        public DateTime F_REQUEST_DATE { get; set; }
        [Display(Name = "رقم الموبيل")]
        public string F_MOBILE_NO { get; set; }
        [Display(Name = "الرقم القومى ")]
        public string F_NATIONAL_ID { get; set; }
        [Display(Name = "العنوان")]
        public string F_TITTLE { get; set; }
        [Display(Name = "نص الطلب")]
        public string F_NOTES { get; set; }
        public short F_STATUS { get; set; }
        public int F_USER_ID { get; set; }
        [Display(Name = "تاريخ الطباعة")]
        public DateTime? F_PRINT_DATE { get; set; }
    }


    public partial class T_REQUEST_DETAILES
    {
        [Key]
        public int F_ID { get; set; }
        [Required]
        [Display(Name = "رقم الطلب")]
        public int F_REQUEST_ID { get; set; }
        [Display(Name = "تاريخ التحديث")]
        public DateTime F_UPDATE_DATE { get; set; }        
        [Required]
        [Display(Name = "نص الطلب")]
        public string F_NOTES { get; set; }
        public short F_STATUS { get; set; }
        public int F_USER_ID { get; set; }
    }


    public class RequestIdDto
    {
        public int Id { get; set; }
    }

}
