//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class V_SPENDDATE
    {
        [Key, Column(Order = 0)]
        [Display(Name = "رقم القيد")]
        public decimal F_MEMBER { get; set; }
        
        [Key, Column(Order = 1)]        
        [Display(Name = " الدفعة")]
        public decimal F_DOFA { get; set; }
        
        [Key, Column(Order = 2)]
        [Display(Name = " السنة")]
        public short F_YEAR { get; set; }
        [Display(Name = "الكود")]
        public decimal F_CODE { get; set; }
        [Display(Name = "المبلغ")]
        public Nullable<decimal> F_VALUE { get; set; }
        [Display(Name = "اسم المستفيد ")]
        public string F_PERSON { get; set; }
        [Display(Name = "رقم الحساب")]
        public string F_ACCOUNTNO { get; set; }
        [Display(Name = "رقم الجيرو")]
        public string GIRO_NO { get; set; }
        [Display(Name = "البنك الرئيسى")]
        public string M_BANK { get; set; }
        [Display(Name = "فرع البنك")]
        public string S_BANK { get; set; }
        [Display(Name = "طريقة الدفع")]
        public Nullable<decimal> F_SPENDWAY { get; set; }
        [Display(Name = "طريقة الدفع")]
        public string SPENDWAY { get; set; }
        [Display(Name = "اسم العضو ")]
        public string MEM_NAME { get; set; }
        [Display(Name = "تاريخ الدفع")]
        public string F_SPENDATE { get; set; }
        [Display(Name = "تاريخ التنفيذ")]
        public string F_SPENDATE_OUT { get; set; }
       
    }
}
