//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class V_T_SPENDPENSION_SELF
    {
        [Display(Name = "العضو")]
        public decimal F_MEMBER { get; set; }
        [Display(Name = "المبلغ")]
        public Nullable<decimal> F_VALUE { get; set; }
        [Display(Name = "الشهر")]
        public Nullable<decimal> F_MONTHS { get; set; }
        [Display(Name = "رقم الشيك")]
        public string F_CHECKNO { get; set; }
        [Display(Name = "رقم الحساب")]
        public string F_ACCOUNTNO { get; set; }
        [Display(Name = "السنة ")]
        public short F_YEAR { get; set; }
        [Display(Name = "طريقه الكشف ")]
        public Nullable<decimal> F_CHECKSTATE { get; set; }
        [Display(Name = "تاريخ الصرف ")]
        public Nullable<System.DateTime> F_SPENDATE { get; set; }
        [Display(Name = "الدفعة")]
        public decimal F_DOFA { get; set; }
        [Display(Name = "البنك الرئيسى")]
        public Nullable<decimal> F_MAINBANK { get; set; }
        [Display(Name = "البنك الفرعى")]
        public Nullable<decimal> F_SUBANK { get; set; }
        [Display(Name = "طريقة الصرف")]
        public Nullable<decimal> F_SPENDWAY { get; set; }
        [Display(Name = "اسم المستلم")]
        public string F_RECEIVER { get; set; }
        [Display(Name = "تاريخ الكشف ")]
        public Nullable<System.DateTime> F_CHECKDATE { get; set; }
        [Display(Name = "حالة الكشف ")]
        public Nullable<decimal> F_CHECKSTATUS { get; set; }
        [Display(Name = "تاريخ الاستلام ")]
        public Nullable<System.DateTime> F_CHECKPAYMENTDATE { get; set; }
        [Display(Name = "نوع الكشف ")]
        public Nullable<byte> F_CHEACK_TYPE { get; set; }
        public Nullable<decimal> F_CHEACK_FLAG { get; set; }
        [Display(Name = "حساب الخزينة ")]
        public Nullable<decimal> F_SARF_ACCOUNT { get; set; }
    }
}
