//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_T_HOLIDAY
    {
        public decimal F_CODE { get; set; }
        public string F_NAME { get; set; }
        public Nullable<decimal> F_FLATRENT { get; set; }
        public string F_NOTES { get; set; }
        public short F_YEAR { get; set; }
        public string F_OWNER { get; set; }
        public string F_ADDRESS { get; set; }
        public Nullable<decimal> F_FLATS_COUNT { get; set; }
        public Nullable<decimal> F_INSURE_VALUE { get; set; }
        public string URL_RESORT_PIC { get; set; }
    }
}
