//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_T_MEDICAL_SAFE
    {
        public int F_YEAR { get; set; }
        public int F_SERIAL { get; set; }
        public decimal F_MEM { get; set; }
        public Nullable<decimal> F_RECVALUE { get; set; }
        public Nullable<System.DateTime> F_RECDATE { get; set; }
        public Nullable<short> F_SAFE_MAN { get; set; }
        public Nullable<decimal> F_PAYVALUE { get; set; }
        public Nullable<byte> F_SELF { get; set; }
        public Nullable<byte> F_CHILDREN_COUNT { get; set; }
        public Nullable<byte> F_FELLOW_COUNT { get; set; }
        public Nullable<byte> F_PARENT_COUNT { get; set; }
        public decimal F_BRANCHNO { get; set; }
        public Nullable<decimal> F_PENALTY { get; set; }
        public Nullable<decimal> F_SAFETYPE { get; set; }
        public Nullable<decimal> F_STAMP { get; set; }
    }
}
