//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class V_T_GOV
    {
        [Key]
        public decimal F_CODE { get; set; }
        public string F_NAME { get; set; }
        [Display(Name = "مبلغ توصيل ")]
        public decimal F_SEND_COST { get; set; }
    }


    public partial class V_SYSCODE
    {
        [Key]
        public int F_CODE { get; set; }
        public int F_TYPE { get; set; }
        
        [Display(Name = "الاسم")]
        public string F_NAME { get; set; }
        [Display(Name = "E الاسم")]
        public string F_NAME_EN { get; set; }
    }


}
