//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class V_T_CENTER
    {
        [Key]
        public decimal F_CODE { get; set; }
        public string F_NAME { get; set; }
        public decimal F_GOV { get; set; }
    }
}
