//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_T_EMPLOYERS
    {
        public long NATIONALNO { get; set; }
        public string F_NAME { get; set; }
        public int F_PHONE_NO { get; set; }
        public long F_MOBILE_NO { get; set; }
        public string F_BRANCH { get; set; }
        public string F_EMAIL { get; set; }
        public string F_IMG_PATH { get; set; }
        public string F_WORK_SIDE { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public Nullable<decimal> F_EMPID { get; set; }
        public Nullable<System.DateTime> PRINTDATE { get; set; }
        public Nullable<System.DateTime> PRINTTIME { get; set; }
        public Nullable<decimal> RECIEPT_NO { get; set; }
        public Nullable<decimal> RECIEPT_YEAR { get; set; }
        public string F_ADDRESS { get; set; }
        public string F_CLASS { get; set; }
        public Nullable<bool> F_CLASS_NO { get; set; }
        public Nullable<byte> BRANCH_NO { get; set; }
    }
}
