//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_T_ACTIVITIES_SAFE
    {
        public short F_BRANCH_NO { get; set; }
        public int F_REC_NO { get; set; }
        public short F_REC_YEAR { get; set; }
        public System.DateTime F_REC_DATE { get; set; }
        public int F_LAST_ACTIVITY_CODE { get; set; }
        public Nullable<short> F_USER_CODE { get; set; }
        public Nullable<int> F_BENEF_CODE { get; set; }
        public string F_BENEF_NAME { get; set; }
        public Nullable<byte> F_COUNT { get; set; }
        public Nullable<decimal> F_DISCOUNT_MEM { get; set; }
        public decimal F_TOTAL_VALUE { get; set; }
        public string F_NOTES { get; set; }
        public string F_USED { get; set; }
        public Nullable<decimal> F_STAMP { get; set; }
        public Nullable<decimal> F_VAT { get; set; }
    }
}
