//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_T_PAYMENT_SAFE_DETAIL
    {
        public decimal RECIPT_NO { get; set; }
        public decimal RECIEPT_YEAR { get; set; }
        public decimal SER { get; set; }
        public decimal DESC_PAY { get; set; }
        public decimal PAY_YEAR { get; set; }
        public Nullable<decimal> PAY_MONTH { get; set; }
        public decimal PAY_VALUE { get; set; }
        public Nullable<decimal> ISHTRAKAT { get; set; }
        public Nullable<decimal> SERVICE_BOX { get; set; }
        public Nullable<decimal> STAMP { get; set; }
        public Nullable<decimal> LATE_VALUE { get; set; }
        public Nullable<decimal> FEE_MEM { get; set; }
        public Nullable<decimal> FEE_ADMIN { get; set; }
        public Nullable<decimal> F_ESSP_CARD { get; set; }
        public Nullable<decimal> SAFE_MAN { get; set; }
        public decimal F_BRANCH { get; set; }
        public Nullable<decimal> CD { get; set; }
        public Nullable<bool> F_USED { get; set; }
        public Nullable<decimal> FEES { get; set; }
    }
}
