//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class V_T_BRANCH_DESCRIPTION
    {
        [Key]
        public int F_BRANCHNO { get; set; }
        [Display(Name = "اسم الفرع")]
        public string F_TITTLE { get; set; }
        [Display(Name = "العنوان")]
        public string F_ADDRESS { get; set; }
        public Nullable<int> F_GAV_ID { get; set; }
        public Nullable<int> F_CENTER_ID { get; set; }
        [Display(Name = "الموبيل")]
        public string F_MOBILE { get; set; }
        [Display(Name = "1 التليفون")]
        public string F_TEL1 { get; set; }
        [Display(Name = " 2 التليفون")]
        public string F_TEL2 { get; set; }
        [Display(Name = "الفاكس")]
        public string F_FAX { get; set; }
        [Display(Name = "البريد الالكترونى")]
        public string F_EMAIL { get; set; }
        public Nullable<float> F_LATITUDE { get; set; }
        public Nullable<float> F_LONGITUDE { get; set; }
        [Display(Name = "اوقات العمل")]
        public string WORK_TIME { get; set; }
        [Display(Name = "مبلغ توصيل ")]
        public decimal F_SEND_COST { get; set; }
    }
}
