//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class V_T_PENALTY
    {
        [Key]
        public decimal F_SER { get; set; }
        public Nullable<short> F_FROMYEAR { get; set; }
        public Nullable<short> F_TOYEAR { get; set; }
        public Nullable<decimal> F_FROMVAL { get; set; }
        public Nullable<decimal> F_TOVAL { get; set; }
        public Nullable<decimal> F_PRCENT { get; set; }
    }
}
