//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class V_T_TRAINING_DESCRIPTION
    {
        [Key]
        public int F_CODE { get; set; }
        [Display(Name = "وصف الدورة ")]
        public string F_TRANING_DES { get; set; }
        [Display(Name = " اسم المحاضر ")]
        public string F_TRAINER_NAME { get; set; }
        [Display(Name = "التليفون")]
        public Nullable<long> F_TRAINER_PHONE { get; set; }
        [Display(Name = "العنوان")]
        public string F_ADDRESS { get; set; }
        [Display(Name = "التاريخ")]
        [DisplayFormat(DataFormatString = "{0:dd MM yyyy}")]
        public Nullable<System.DateTime> F_DATE { get; set; }
        [Display(Name = "المبلغ")]
        public string F_VALUE { get; set; }
        [Display(Name = "قيمة الخصم")]
        public Nullable<byte> F_DISCOUNT { get; set; }
        [Display(Name = "صورة الموقع")]
        public string F_URL_PIC { get; set; }
    }
}
