//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_T_GUIDE_CODE
    {
        public byte F_GUIDE_ID { get; set; }
        public string F_NAME { get; set; }
        public Nullable<bool> F_HIDDEN { get; set; }
    }


    public partial class V_PENALTY
    {
        public int F_SER { get; set; }
        public int F_FROMYEAR { get; set; }
        public int F_TOYEAR { get; set; }
        public int F_FROMVAL { get; set; }
        public int F_TOVAL { get; set; }
        public int F_PRCENT { get; set; }
    }
}
