//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class V_T_FLATS
    {
        [Key]
        [Column(Order = 1)]
        public decimal F_HOLIDAYCODE { get; set; }

        [Key]
        [Column(Order = 2)]
        [Display(Name = "رقم الشقه")]
        [DisplayFormat(DataFormatString = "{0:#}")]
        public decimal F_CODE { get; set; }

        [Key]
        [Column(Order = 3)]
        [Display(Name = "السنه")]
        public short F_YEAR { get; set; }

        [Key]
        [Column(Order = 4)]
        [DisplayFormat(DataFormatString = "{0:#}")]
        [Display(Name = "الاسبوع")]
        public decimal F_WEEK { get; set; }

        [Display(Name = "تكلفه الاسبوع ")]
        public Nullable<decimal> F_WEEKCOST { get; set; }
        [Display(Name = "ايجار الاسبوع ")]
        public Nullable<decimal> F_WEEKRENT { get; set; }
        [Display(Name = "رقم العضو  ")]
        public Nullable<decimal> F_MEM { get; set; }
        [Display(Name = "رقم الايصال  ")]
        public string F_RECEIPTNO { get; set; }
        [Display(Name = "تاريخ الايصال")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> F_RECDATE { get; set; }
        [Display(Name = "مبلغ التامين")]
        public Nullable<decimal> F_INSURCOST { get; set; }


        [Display(Name = "تكلفه التاليف")]
        public Nullable<decimal> F_DAMAGECOST { get; set; }
        public Nullable<decimal> F_INSURFINE { get; set; }
        public Nullable<decimal> F_REST { get; set; }
        public string F_DAMAGEDESC { get; set; }
        [Display(Name = "المالك")]
        public string F_OWNER { get; set; }
        public string F_OWNERADDRESS { get; set; }
        public string F_OWNERTEL { get; set; }
        public Nullable<decimal> F_DAMAGEPAY { get; set; }
        public Nullable<decimal> F_STAMP { get; set; }

        [Display(Name = "وصف الشقة")]
        public string F_FLAT_DESC { get; set; }

        [Display(Name = "من")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        public Nullable<System.DateTime> F_FROM { get; set; }

        [Display(Name = "الى")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        public Nullable<System.DateTime> F_TO { get; set; }

        [Display(Name = "المكان")]
        public string F_PLACES { get; set; }
        public Nullable<bool> F_FLAT_TAKING { get; set; }
        public Nullable<bool> F_FLAT_LEAVING { get; set; }
        public Nullable<decimal> F_SAFE_MAN { get; set; }
        public Nullable<bool> F_PAYMENT_TYPE { get; set; }
        public Nullable<decimal> F_PAYED { get; set; }
        public Nullable<decimal> F_DELAYED_VALUE { get; set; }
        public Nullable<decimal> F_REST_TO_MEM { get; set; }
        public Nullable<decimal> F_REST_ON_MEM { get; set; }
        public Nullable<bool> F_RECEIPT_TYPE { get; set; }
        public decimal F_FLAT_STATUS { get; set; }
        public Nullable<decimal> F_RECEPITNO_R { get; set; }
    }

    public partial class V_FLAT_PIC
    {
        //ID as Indx ,F_CODE, F_YEAR, FLAT_URL_PIC, FLG, THUMBNAIL 
        [Key]
        public int INDX { get; set; }
       
        [Display(Name = "رقم الشقه")]
        public decimal F_CODE { get; set; }
       
        [Display(Name = "السنه")]
        public short F_YEAR { get; set; }   
        public string FLAT_URL_PIC { get; set; }
        public int FLG { get; set; }      
        public string THUMBNAIL { get; set; }
    }

}
