//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_T_PAYMENT_SAFE
    {
        public decimal RECIEPT_NO { get; set; }
        public System.DateTime RECIEPT_DATE { get; set; }
        public decimal RECIEPT_YEAR { get; set; }
        public Nullable<decimal> RECIEPT_VALUE { get; set; }
        public decimal SAFE_MAN { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> F_MEM { get; set; }
        public string MEM_NAME_NEW { get; set; }
        public Nullable<decimal> GRDUATION_YEAR { get; set; }
        public Nullable<decimal> F_PENALTY { get; set; }
        public Nullable<decimal> F_SITETYPE { get; set; }
        public Nullable<decimal> F_CARD_VALUE { get; set; }
        public Nullable<decimal> CD_VALUE { get; set; }
        public Nullable<decimal> TASNEF_CODE { get; set; }
        public Nullable<decimal> SDAD_TYPE { get; set; }
        public Nullable<decimal> PAY_TAKSET { get; set; }
        public string MEM_ID { get; set; }
        public decimal F_BRANCH { get; set; }
        public Nullable<bool> F_USED { get; set; }
    }
}
