//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPMemberService
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;

    public partial class V_USERS
    {
        [Key]
        public int USER_CODE { get; set; }
        [Display(Name = "الاسم ")]
        public string FULL_NAME { get; set; }
        [Display(Name = "اسم المستخدم ")]
        public string USER_NAME { get; set; }
        [Display(Name = "كلمة المرور ")]
        public string PASSWORD { get; set; }

        [Display(Name = "الفرع")]
        public short BRANCH_NO { get; set; }
        public short STATUS { get; set; }
        public short IS_ADMIN { get; set; }
        public short MEDICAL { get; set; }
        public short RESORTS { get; set; }
        public short YOUTH_CARD { get; set; }
        public short MEMBER { get; set; }
        public short ACCOUNT { get; set; }
        public short ACTIVITY { get; set; }
        public short ASSEMBLY { get; set; }
        public short BRANCH { get; set; }
        public short PRINT_DOC { get; set; }
        public short PRINT_MEM_CARD { get; set; }
        public short SAFE_USER { get; set; }
        public short SAFE_MAIN_ID { get; set; }
        public string MAC_ADDRESS { get; set; }        

    }
}
